### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by cloudbehl**
- Charts which values can not be negative shouldn't show negative labels on axis
- CPU Utilization values are wrong

### CODE REVIEW

**Comment by cloudbehl** [comment]
@GowthamShanmugam There are few metrics changed, can you have a look. I have changed a CPU utilization metric on host dashboard and brick utilization in the brick dashboard page.

Please make the default queries change accordingly to the new queries for alerts page.

**Comment by GowthamShanmugam** [comment]
@cloudbehl i will change alert handler metric templates also

**Comment by cloudbehl** [comment]
@GowthamShanmugam are you done with the changes? can we merge this patch?

**Comment by GowthamShanmugam** [comment]
@cloudbehl i have verified with your patch, no need to change in alerting side, alerts are received for new metric change also

**Pull request merged**
