### PR TITLE
Changing units for throughput and latency panel in disk dashboard

### PR DESCRIPTION
**Pull request by cloudbehl**
tendrl-bug-id: Tendrl/monitoring-integration#507
bugzilla: 1595052

Signed-off-by: Ankush Behl <cloudbehl@gmail.com>

### CODE REVIEW

**Comment by cloudbehl** [comment]
@r0h4n asked few questions on Bugzilla. Needs to be addressed before merging. 

https://bugzilla.redhat.com/show_bug.cgi?id=1595052

I will remove WIP from the PR heading once the comment is addressed.

**Comment by r0h4n** [comment]
@cloudbehl  any updates?

**Comment by cloudbehl** [comment]
@r0h4n I need to update this PR as per martin's comment. Its in progress will be done by EOD today.

**Comment by nthomas-redhat** [comment]
@cloudbehl , verified this?

**Comment by cloudbehl** [comment]
@r0h4n @nthomas-redhat Its verified

**Pull request merged**
