### PR TITLE
Modified description of IOPS panel in volume dashbaord

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
tendrl-bug-id: Tendrl/monitoring-integration#559
bugzilla: 1614270

Signed-off-by: GowthamShanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
iops

@mbukatov @julienlim

**Comment by cloudbehl** [comment]
@GowthamShanmugam martin told us to add about the disabled[1] scenario and which we still have not considered that scenario in the suggestion you provided.

@nthomas-redhat @shtripat any suggestions on that part.

[1]. https://bugzilla.redhat.com/show_bug.cgi?id=1614270#c1

**Comment by GowthamShanmugam** [comment]
profiling_disable


@cloudbehl

**Comment by nthomas-redhat** [comment]
> @GowthamShanmugam martin told us to add about the disabled[1] scenario and which we still have not considered that scenario in the suggestion you provided.
> 
> @nthomas-redhat @shtripat any suggestions on that part.
> 
> [1]. https://bugzilla.redhat.com/show_bug.cgi?id=1614270#c1

Latest screenshot looks good

**Pull request merged**
