### PR TITLE
Skipping no_data alert in grafana

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
tendrl-bug-id: Tendrl/monitoring-integration#117

Signed-off-by: root <root@dhcp41-176.lab.eng.blr.redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@r0h4n @rishubhjain  please review

**Comment by GowthamShanmugam** [comment]
@nthomas-redhat

**Comment by r0h4n** [comment]
@GowthamShanmugam  plz fix merge conflicts

**Comment by GowthamShanmugam** [comment]
@r0h4n please review

**Comment by GowthamShanmugam** [comment]
changes done

**Pull request merged**
