### PR TITLE
Made the graphs connected for null values and fixed healing counters

### PR DESCRIPTION
**Pull request by cloudbehl**
tendrl-bug-id: #120

### CODE REVIEW

**Comment by cloudbehl** [comment]
@rishubhjain Please verify this patch and provide a Ack!

**Comment by rishubhjain** [comment]
@cloudbehl Tested the PR, doesnot need any change from Monitoring-integration side to support this PR.
I will test whether the values are proper or not

**Comment by cloudbehl** [comment]
@r0h4n Yes it's verified!

**Comment by rishubhjain** [comment]
tendrl-bug-id: Tendrl/monitoring-integration#91

**Pull request merged**
