### PR TITLE
Increase graphite retention from default 1 day to 180 days

### PR DESCRIPTION
**Pull request by anmolbabu**
tendrl-bug-id: Tendrl/monitoring-integration#95
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by anmolbabu** [comment]
@rishubhjain @TimothyAsir @nthomas-redhat @r0h4n Please review

To be verified

**Comment by rishubhjain** [comment]
@anmolbabu Have you tested the changes?

**Comment by r0h4n** [comment]
@anmolbabu work with @mbukatov to file an issue to get these new config files handled by tendrl-ansible

also provide changes required to current manual install guide for 1.5.2

https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.5.2-(install-guide)

**Comment by anmolbabu** [comment]
@r0h4n Ok so you are saying these can better be handled by tendrl-ansible instead of via tendrl module as it is a config change of a component(graphite) that is not tendrl component?

**Comment by r0h4n** [comment]
Sorry for confusing. Just ensure these new config files are correctly mentioned if required in 1.5.2 install guide

@mbukatov do you need any inputs so that tendrl-ansible is aware of these new config files?

**Comment by anmolbabu** [comment]
>Just ensure these new config files are correctly mentioned if required in 1.5.2 install guide

Ack. They happen internally as part of rpm installation and hence they are not required in install guide.

**Comment by mbukatov** [comment]
It seems that this new config file will be used as it is provided by rpm package, so no changes in tendrl-ansible are needed.

**Comment by anmolbabu** [comment]
>It seems that this new config file will be used as it is provided by rpm package, so no changes in tendrl-ansible are needed.

@mbukatov There is a change https://github.com/Tendrl/monitoring-integration/pull/129/files#diff-a2c8ca4c97d4213cb2f7e94c64e599c1R14 to line 16 are new lines

**Pull request merged**
