### PR TITLE
New dashboard added for milestone 3

### PR DESCRIPTION
**Pull request by cloudbehl**
#tendrl-bug-id:  https://github.com/Tendrl/monitoring-integration/issues/92

### CODE REVIEW

**Comment by nthomas-redhat** [comment]
Link this with git issue

**Comment by cloudbehl** [comment]
@rishubhjain please review.

**Comment by r0h4n** [comment]
@cloudbehl verified?

**Comment by cloudbehl** [comment]
@rishubhjain please verify and provide an ack!

@r0h4n I have verified it.Let Rishabh provide an ack and we can merge it then.

**Comment by rishubhjain** [comment]
@cloudbehl @r0h4n Verified Please merge

**Pull request merged**
