### PR TITLE
Removed Weeks Remaining and growth rate  panels from  Host dashboard and cluster dashboard

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
bugzilla: 1614005
tendrl-bug-id: Tendrl/monitoring-integration#564

Signed-off-by: GowthamShanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
cluster_dashboard
host_dashboard


@cloudbehl @julienlim @mbukatov

**Comment by shtripat** [comment]
Looks good as per https://bugzilla.redhat.com/show_bug.cgi?id=1614005#c9

**Comment by cloudbehl** [comment]
@julienlim can you review this patch. After stretching the panels the graphs were looking too big.

So we reduced the width of some panels and made it into two rows.

 @GowthamShanmugam can you attach the original screenshots. So @julienlim can see the difference.

**Comment by GowthamShanmugam** [comment]
before_remove_in_cluster
before_remove_in_host


Before removing weekly remaining and weekly growth rate  panels

**Comment by GowthamShanmugam** [comment]
@cloudbehl i have added both

**Comment by julienlim** [comment]
Reviewed https://github.com/Tendrl/monitoring-integration/pull/565#issuecomment-420219197 and looks fine to me.

@GowthamShanmugam @nthomas-redhat @cloudbehl

**Comment by cloudbehl** [comment]
@julienlim Thanks!

@GowthamShanmugam is this patch verified?

**Pull request merged**
