### PR TITLE
Make tendrl compatible with Grafana 5.x.x

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
tendrl-bug-id: Tendrl/monitoring-integration/issues/357

Signed-off-by: Gowthamshanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@r0h4n @nthomas-redhat @shtripat please review

**Comment by GowthamShanmugam** [comment]
Tested

**Comment by nthomas-redhat** [comment]
> Tested

Have you tested all the dashboards? And is this the only issue if you upgrade to 5.0.0.0?
Is this change backward compatible with older grafana releases?

**Comment by GowthamShanmugam** [comment]
@nthomas-redhat Yes i checked all dashbaord, this is the issue, i have tested this change with older grafana also, both works fine

**Pull request merged**
