### PR TITLE
Removed Subvolume panel from Volume dashboard

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
bugzilla: 1614263
tendrl-bug-id: Tendrl/monitoring-integration#570

Signed-off-by: GowthamShanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
removed_sub_vol



@cloudbehl i removed this from code directly not removed from grafana and copied json, please review this PR and check my changes are correct

**Comment by GowthamShanmugam** [comment]
I tested dashboard is looks fine

**Comment by GowthamShanmugam** [comment]
@mbukatov @julienlim

**Comment by shtripat** [comment]
Looks good to me now

**Comment by cloudbehl** [comment]
@GowthamShanmugam @shtripat  I will recommend we should not reduce the alignment of any panel. We can increase it but reduction may lead to some regressions. 

I will recommend we change the rebalance status back to the original width. If we want to change the width of geo-rep then we can reduce the width of the rebalance panel.

**Comment by GowthamShanmugam** [comment]
@cloudbehl i reverted back that new change

**Pull request merged**
