### PR TITLE
Added keyerror in alert exception handler

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@rishubhjain @r0h4n please review

**Comment by rishubhjain** [comment]
@GowthamShanmugam Please attach bug id
Rest looks good to me
@r0h4n @anivargi Please review

**Comment by GowthamShanmugam** [comment]
@r0h4n @rishubhjain  I tried to reproduce, may give a key error because of grafana connection issue, this error will come when alert is caught by monitoring integration it will again query grafana using received alert id. if any connection issue happened at that time it will give empty result. so at that time, keyerror may come. I tried but I can't reproduce keyError.

**Comment by GowthamShanmugam** [comment]
@rishubhjain i feel this kind of error came when we worked on the same machine at both side :)

**Comment by r0h4n** [comment]
Closing this for now, let me know if regression actually exists

**Pull request closed without merging**
