### PR TITLE
Update tendrl-monitoring-integration.spec

### PR DESCRIPTION
**Pull request by shtripat**

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
LGTM

This patch can be merged. Tested.

**Comment by TimothyAsirJeyasing** [comment]
This patch can be merged. I have tested the package installation using this patch.

**Comment by r0h4n** [comment]
"tendrl-commons" already requires "python2-ruamel-yaml" 

Please remove the "Requires: python2-ruamel-yaml" altogether

**Comment by r0h4n** [comment]
Fixes: https://github.com/Tendrl/monitoring-integration/issues/58

**Pull request merged**
