### PR TITLE
Removed logging yaml file from monitoring integration

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
tendrl-bug-id: Tendrl/monitoring-integration#134
tendrl-bug-id: Tendrl/monitoring-integration#78
Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@rishubhjain @r0h4n please review

**Comment by rishubhjain** [comment]
@GowthamShanmugam Is it tested?

**Comment by r0h4n** [comment]
cc: @mbukatov

**Comment by GowthamShanmugam** [comment]
@rishubhjain yes

**Pull request merged**
